# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addImage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 695)
        MainWindow.setStyleSheet("background-color: #f5f5f5;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnInput = QtWidgets.QPushButton(self.centralwidget)
        self.btnInput.setGeometry(QtCore.QRect(10, 10, 131, 31))
        self.btnInput.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnInput.setObjectName("btnInput")
        self.lbImg = QtWidgets.QLabel(self.centralwidget)
        self.lbImg.setGeometry(QtCore.QRect(10, 50, 771, 461))
        self.lbImg.setStyleSheet("text-align: center")
        self.lbImg.setText("")
        self.lbImg.setScaledContents(True)
        self.lbImg.setObjectName("lbImg")
        self.txtLabel = QtWidgets.QTextEdit(self.centralwidget)
        self.txtLabel.setGeometry(QtCore.QRect(170, 530, 471, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        self.txtLabel.setFont(font)
        self.txtLabel.setStyleSheet("padding: 1px;\n"
"border: 1px solid #ccc")
        self.txtLabel.setObjectName("txtLabel")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 530, 141, 41))
        font = QtGui.QFont()
        font.setFamily("JetBrains Mono")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #555")
        self.label.setObjectName("label")
        self.btnAdd = QtWidgets.QPushButton(self.centralwidget)
        self.btnAdd.setGeometry(QtCore.QRect(220, 590, 381, 41))
        self.btnAdd.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAdd.setStyleSheet("background-color: #fa5230;\n"
"border: 1px solid #ccc;\n"
"color: #fff;\n"
"font-size: 18px;\n"
"border-radius: 6px;")
        self.btnAdd.setObjectName("btnAdd")
        self.lbStatus = QtWidgets.QLabel(self.centralwidget)
        self.lbStatus.setGeometry(QtCore.QRect(210, 10, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(-1)
        self.lbStatus.setFont(font)
        self.lbStatus.setStyleSheet("color: green;\n"
"font-size: 20px;")
        self.lbStatus.setText("")
        self.lbStatus.setObjectName("lbStatus")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnInput.setText(_translate("MainWindow", "Choose File:"))
        self.txtLabel.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'JetBrains Mono\'; font-size:12pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "Label Name:"))
        self.btnAdd.setText(_translate("MainWindow", "ADD TO COLLECTION"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
