# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(313, 256)
        MainWindow.setStyleSheet("background-color: #fff;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnAddFace = QtWidgets.QPushButton(self.centralwidget)
        self.btnAddFace.setGeometry(QtCore.QRect(40, 50, 221, 41))
        self.btnAddFace.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnAddFace.setStyleSheet("border: 1px solid #fa5230;\n"
                                      "border-radius: 6px;\n"
                                      "background-color: #fff;\n"
                                      "font-size: 18px;")
        self.btnAddFace.setObjectName("btnAddFace")
        self.btnDetect = QtWidgets.QPushButton(self.centralwidget)
        self.btnDetect.setGeometry(QtCore.QRect(40, 120, 221, 41))
        self.btnDetect.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btnDetect.setStyleSheet("background-color: #fa5230;\n"
                                     "border: 1px solid #ccc;\n"
                                     "color: #fff;\n"
                                     "font-size: 18px;\n"
                                     "border-radius: 6px;")
        self.btnDetect.setObjectName("btnDetect")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 313, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnAddFace.setText(_translate("MainWindow", "Thêm khuôn mặt"))
        self.btnDetect.setText(_translate("MainWindow", "Nhận diện khuôn mặt"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    # Open Add Face form
    MainWindow.show()
    sys.exit(app.exec_())
